name: rakuda
description: Quick and dirty HTTP API client factory for Dart.
version: 0.1.0
homepage: https://github.com/YusukeIwaki/rakuda
repository: https://github.com/YusukeIwaki/rakuda

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.20.1
dependencies:
  http: ^0.13.4
  path: ^1.8.1
