name: Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fail-fast: false
        sdk:
          - beta
          - dev
          - stable
          - 2.12.4
          - 2.14.4

    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ matrix.sdk }}
      - name: Install dependencies
        run: dart pub get
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze project source
        run: dart analyze
      - name: Run tests
        run: dart test
      - name: Execute examples
        run: dart examples/github_api.dart GET /repos/YusukeIwaki/rakuda
